from objects import *
from objects.atom import Atom
from objects.colors import Color

ATOM_FACTORY = {
    # Color codes:
    # - Alkali metal: RED
    # - Alkaline earth metal: ORANGE
    # - Transition metal: SILVER
    # - Post-transition metal: MAGENTA
    # - Metalloid: YELLOW
    # - Polyatomic nonmetal: GREEN
    # - Diatomic nonmetal: PURPLE
    # - Noble gas: CYAN
    # - Other: GRAY
    1: {
        "H": (lambda: Atom("phong", Color.PURPLE, 1, "H"), 1),
        "He": (lambda: Atom("phong", Color.CYAN, 2, "He"), 18),
    },
    2: {
        "Li": (lambda: Atom("phong", Color.RED, 3, "Li"), 1),
        "Be": (lambda: Atom("phong", Color.ORANGE, 4, "Be"), 2),
        "B": (lambda: Atom("phong", Color.YELLOW, 5, "B"), 13),
        "C": (lambda: Atom("phong", Color.GREEN, 6, "C"), 14),
        "N": (lambda: Atom("phong", Color.PURPLE, 7, "N"), 15),
        "O": (lambda: Atom("phong", Color.PURPLE, 8, "O"), 16),
        "F": (lambda: Atom("phong", Color.PURPLE, 9, "F"), 17),
        "Ne": (lambda: Atom("phong", Color.CYAN, 10, "Ne"), 18),
    },
    3: {
        "Na": (lambda: Atom("phong", Color.RED, 11, "Na"), 1),
        "Mg": (lambda: Atom("phong", Color.ORANGE, 12, "Mg"), 2),
        "Al": (lambda: Atom("phong", Color.MAGENTA, 13, "Al"), 13),
        "Si": (lambda: Atom("phong", Color.YELLOW, 14, "Si"), 14),
        "P": (lambda: Atom("phong", Color.GREEN, 15, "P"), 15),
        "S": (lambda: Atom("phong", Color.GREEN, 16, "S"), 16),
        "Cl": (lambda: Atom("phong", Color.PURPLE, 17, "Cl"), 17),
        "Ar": (lambda: Atom("phong", Color.CYAN, 18, "Ar"), 18),
    },
    4: {
        "K": (lambda: Atom("phong", Color.RED, 19, "K"), 1),
        "Ca": (lambda: Atom("phong", Color.ORANGE, 20, "Ca"), 2),
        "Sc": (lambda: Atom("phong", Color.SILVER, 21, "Sc"), 3),
        "Ti": (lambda: Atom("phong", Color.SILVER, 22, "Ti"), 4),
        "V": (lambda: Atom("phong", Color.SILVER, 23, "V"), 5),
        "Cr": (lambda: Atom("phong", Color.SILVER, 24, "Cr"), 6),
        "Mn": (lambda: Atom("phong", Color.SILVER, 25, "Mn"), 7),
        "Fe": (lambda: Atom("phong", Color.SILVER, 26, "Fe"), 8),
        "Co": (lambda: Atom("phong", Color.SILVER, 27, "Co"), 9),
        "Ni": (lambda: Atom("phong", Color.SILVER, 28, "Ni"), 10),
        "Cu": (lambda: Atom("phong", Color.SILVER, 29, "Cu"), 11),
        "Zn": (lambda: Atom("phong", Color.SILVER, 30, "Zn"), 12),
        "Ga": (lambda: Atom("phong", Color.MAGENTA, 31, "Ga"), 13),
        "Ge": (lambda: Atom("phong", Color.YELLOW, 32, "Ge"), 14),
        "As": (lambda: Atom("phong", Color.YELLOW, 33, "As"), 15),
        "Se": (lambda: Atom("phong", Color.GREEN, 34, "Se"), 16),
        "Br": (lambda: Atom("phong", Color.PURPLE, 35, "Br"), 17),
        "Kr": (lambda: Atom("phong", Color.CYAN, 36, "Kr"), 18),
    },
    5: {
        "Rb": (lambda: Atom("phong", Color.RED, 37, "Rb"), 1),
        "Sr": (lambda: Atom("phong", Color.ORANGE, 38, "Sr"), 2),
        "Y": (lambda: Atom("phong", Color.SILVER, 39, "Y"), 3),
        "Zr": (lambda: Atom("phong", Color.SILVER, 40, "Zr"), 4),
        "Nb": (lambda: Atom("phong", Color.SILVER, 41, "Nb"), 5),
        "Mo": (lambda: Atom("phong", Color.SILVER, 42, "Mo"), 6),
        "Tc": (lambda: Atom("phong", Color.SILVER, 43, "Tc"), 7),
        "Ru": (lambda: Atom("phong", Color.SILVER, 44, "Ru"), 8),
        "Rh": (lambda: Atom("phong", Color.SILVER, 45, "Rh"), 9),
        "Pd": (lambda: Atom("phong", Color.SILVER, 46, "Pd"), 10),
        "Ag": (lambda: Atom("phong", Color.SILVER, 47, "Ag"), 11),
        "Cd": (lambda: Atom("phong", Color.SILVER, 48, "Cd"), 12),
        "In": (lambda: Atom("phong", Color.MAGENTA, 49, "In"), 13),
        "Sn": (lambda: Atom("phong", Color.MAGENTA, 50, "Sn"), 14),
        "Sb": (lambda: Atom("phong", Color.YELLOW, 51, "Sb"), 15),
        "Te": (lambda: Atom("phong", Color.YELLOW, 52, "Te"), 16),
        "I": (lambda: Atom("phong", Color.PURPLE, 53, "I"), 17),
        "Xe": (lambda: Atom("phong", Color.CYAN, 54, "Xe"), 18),
    },
    6: {
        "Cs": (lambda: Atom("phong", Color.RED, 55, "Cs"), 1),
        "Ba": (lambda: Atom("phong", Color.ORANGE, 56, "Ba"), 2),
        "La": (lambda: Atom("phong", Color.GRAY, 57, "La"), 3),
        "Hf": (lambda: Atom("phong", Color.SILVER, 72, "Hf"), 4),
        "Ta": (lambda: Atom("phong", Color.SILVER, 73, "Ta"), 5),
        "W": (lambda: Atom("phong", Color.SILVER, 74, "W"), 6),
        "Re": (lambda: Atom("phong", Color.SILVER, 75, "Re"), 7),
        "Os": (lambda: Atom("phong", Color.SILVER, 76, "Os"), 8),
        "Ir": (lambda: Atom("phong", Color.SILVER, 77, "Ir"), 9),
        "Pt": (lambda: Atom("phong", Color.SILVER, 78, "Pt"), 10),
        "Au": (lambda: Atom("phong", Color.SILVER, 79, "Au"), 11),
        "Hg": (lambda: Atom("phong", Color.SILVER, 80, "Hg"), 12),
        "Tl": (lambda: Atom("phong", Color.MAGENTA, 81, "Tl"), 13),
        "Pb": (lambda: Atom("phong", Color.MAGENTA, 82, "Pb"), 14),
        "Bi": (lambda: Atom("phong", Color.MAGENTA, 83, "Bi"), 15),
        "Po": (lambda: Atom("phong", Color.MAGENTA, 84, "Po"), 16),
        "At": (lambda: Atom("phong", Color.YELLOW, 85, "At"), 17),
        "Rn": (lambda: Atom("phong", Color.CYAN, 86, "Rn"), 18),
    },
    7: {
        "Fr": (lambda: Atom("phong", Color.RED, 87, "Fr"), 1),
        "Ra": (lambda: Atom("phong", Color.ORANGE, 88, "Ra"), 2),
        "Ac": (lambda: Atom("phong", Color.GRAY, 89, "Ac"), 3),
        "Rf": (lambda: Atom("phong", Color.SILVER, 104, "Rf"), 4),
        "Db": (lambda: Atom("phong", Color.SILVER, 105, "Db"), 5),
        "Sg": (lambda: Atom("phong", Color.SILVER, 106, "Sg"), 6),
        "Bh": (lambda: Atom("phong", Color.SILVER, 107, "Bh"), 7),
        "Hs": (lambda: Atom("phong", Color.SILVER, 108, "Hs"), 8),
        "Mt": (lambda: Atom("phong", Color.SILVER, 109, "Mt"), 9),
        "Ds": (lambda: Atom("phong", Color.SILVER, 110, "Ds"), 10),
        "Rg": (lambda: Atom("phong", Color.SILVER, 111, "Rg"), 11),
        "Cn": (lambda: Atom("phong", Color.SILVER, 112, "Cn"), 12),
        "Nh": (lambda: Atom("phong", Color.MAGENTA, 113, "Nh"), 13),
        "Fl": (lambda: Atom("phong", Color.MAGENTA, 114, "Fl"), 14),
        "Mc": (lambda: Atom("phong", Color.MAGENTA, 115, "Mc"), 15),
        "Lv": (lambda: Atom("phong", Color.MAGENTA, 116, "Lv"), 16),
        "Ts": (lambda: Atom("phong", Color.YELLOW, 117, "Ts"), 17),
        "Og": (lambda: Atom("phong", Color.CYAN, 118, "Og"), 18),
    },
}

ATOM_DICT = {
    # fmt: off
    "H": {"name": "Hydrogen", "atomic_number": 1, "mass": 1.008, "electrons": 1, "period": 1, "group": 1, "category": "Nonmetal"},
    "He": {"name": "Helium", "atomic_number": 2, "mass": 4.003, "electrons": 2, "period": 1, "group": 18, "category": "Noble gas"},
    "Li": {"name": "Lithium", "atomic_number": 3, "mass": 6.941, "electrons": 3, "period": 2, "group": 1, "category": "Alkali metal"},
    "Be": {"name": "Beryllium", "atomic_number": 4, "mass": 9.012, "electrons": 4, "period": 2, "group": 2, "category": "Alkaline earth metal"},
    "B": {"name": "Boron", "atomic_number": 5, "mass": 10.811, "electrons": 5, "period": 2, "group": 13, "category": "Metalloid"},
    "C": {"name": "Carbon", "atomic_number": 6, "mass": 12.011, "electrons": 6, "period": 2, "group": 14, "category": "Nonmetal"},
    "N": {"name": "Nitrogen", "atomic_number": 7, "mass": 14.007, "electrons": 7, "period": 2, "group": 15, "category": "Nonmetal"},
    "O": {"name": "Oxygen", "atomic_number": 8, "mass": 15.999, "electrons": 8, "period": 2, "group": 16, "category": "Nonmetal"},
    "F": {"name": "Fluorine", "atomic_number": 9, "mass": 18.998, "electrons": 9, "period": 2, "group": 17, "category": "Halogen"},
    "Ne": {"name": "Neon", "atomic_number": 10, "mass": 20.180, "electrons": 10, "period": 2, "group": 18, "category": "Noble gas"},
    "Na": {"name": "Sodium", "atomic_number": 11, "mass": 22.990, "electrons": 11, "period": 3, "group": 1, "category": "Alkali metal"},
    "Mg": {"name": "Magnesium", "atomic_number": 12, "mass": 24.305, "electrons": 12, "period": 3, "group": 2, "category": "Alkaline earth metal"},
    "Al": {"name": "Aluminum", "atomic_number": 13, "mass": 26.982, "electrons": 13, "period": 3, "group": 13, "category": "Post-transition metal"},
    "Si": {"name": "Silicon", "atomic_number": 14, "mass": 28.086, "electrons": 14, "period": 3, "group": 14, "category": "Metalloid"},
    "P": {"name": "Phosphorus", "atomic_number": 15, "mass": 30.974, "electrons": 15, "period": 3, "group": 15, "category": "Nonmetal"},
    "S": {"name": "Sulfur", "atomic_number": 16, "mass": 32.065, "electrons": 16, "period": 3, "group": 16, "category": "Nonmetal"},
    "Cl": {"name": "Chlorine", "atomic_number": 17, "mass": 35.453, "electrons": 17, "period": 3, "group": 17, "category": "Halogen"},
    "Ar": {"name": "Argon", "atomic_number": 18, "mass": 39.948, "electrons": 18, "period": 3, "group": 18, "category": "Noble gas"},
    "K": {"name": "Potassium", "atomic_number": 19, "mass": 39.098, "electrons": 19, "period": 4, "group": 1, "category": "Alkali metal"},
    "Ca": {"name": "Calcium", "atomic_number": 20, "mass": 40.078, "electrons": 20, "period": 4, "group": 2, "category": "Alkaline earth metal"},
    "Sc": {"name": "Scandium", "atomic_number": 21, "mass": 44.956, "electrons": 21, "period": 4, "group": 3, "category": "Transition metal"},
    "Ti": {"name": "Titanium", "atomic_number": 22, "mass": 47.867, "electrons": 22, "period": 4, "group": 4, "category": "Transition metal"},
    "V": {"name": "Vanadium", "atomic_number": 23, "mass": 50.942, "electrons": 23, "period": 4, "group": 5, "category": "Transition metal"},
    "Cr": {"name": "Chromium", "atomic_number": 24, "mass": 51.996, "electrons": 24, "period": 4, "group": 6, "category": "Transition metal"},
    "Mn": {"name": "Manganese", "atomic_number": 25, "mass": 54.938, "electrons": 25, "period": 4, "group": 7, "category": "Transition metal"},
    "Fe": {"name": "Iron", "atomic_number": 26, "mass": 55.845, "electrons": 26, "period": 4, "group": 8, "category": "Transition metal"},
    "Co": {"name": "Cobalt", "atomic_number": 27, "mass": 58.933, "electrons": 27, "period": 4, "group": 9, "category": "Transition metal"},
    "Ni": {"name": "Nickel", "atomic_number": 28, "mass": 58.693, "electrons": 28, "period": 4, "group": 10, "category": "Transition metal"},
    "Cu": {"name": "Copper", "atomic_number": 29, "mass": 63.546, "electrons": 29, "period": 4, "group": 11, "category": "Transition metal"},
    "Zn": {"name": "Zinc", "atomic_number": 30, "mass": 65.380, "electrons": 30, "period": 4, "group": 12, "category": "Transition metal"},
    "Ga": {"name": "Gallium", "atomic_number": 31, "mass": 69.723, "electrons": 31, "period": 4, "group": 13, "category": "Post-transition metal"},
    "Ge": {"name": "Germanium", "atomic_number": 32, "mass": 72.640, "electrons": 32, "period": 4, "group": 14, "category": "Metalloid"},
    "As": {"name": "Arsenic", "atomic_number": 33, "mass": 74.922, "electrons": 33, "period": 4, "group": 15, "category": "Metalloid"},
    "Se": {"name": "Selenium", "atomic_number": 34, "mass": 78.960, "electrons": 34, "period": 4, "group": 16, "category": "Nonmetal"},
    "Br": {"name": "Bromine", "atomic_number": 35, "mass": 79.904, "electrons": 35, "period": 4, "group": 17, "category": "Halogen"},
    "Kr": {"name": "Krypton", "atomic_number": 36, "mass": 83.798, "electrons": 36, "period": 4, "group": 18, "category": "Noble gas"},
    "Rb": {"name": "Rubidium", "atomic_number": 37, "mass": 85.468, "electrons": 37, "period": 5, "group": 1, "category": "Alkali metal"},
    "Sr": {"name": "Strontium", "atomic_number": 38, "mass": 87.620, "electrons": 38, "period": 5, "group": 2, "category": "Alkaline earth metal"},
    "Y": {"name": "Yttrium", "atomic_number": 39, "mass": 88.906, "electrons": 39, "period": 5, "group": 3, "category": "Transition metal"},
    "Zr": {"name": "Zirconium", "atomic_number": 40, "mass": 91.224, "electrons": 40, "period": 5, "group": 4, "category": "Transition metal"},
    "Nb": {"name": "Niobium", "atomic_number": 41, "mass": 92.906, "electrons": 41, "period": 5, "group": 5, "category": "Transition metal"},
    "Mo": {"name": "Molybdenum", "atomic_number": 42, "mass": 95.940, "electrons": 42, "period": 5, "group": 6, "category": "Transition metal"},
    "Tc": {"name": "Technetium", "atomic_number": 43, "mass": 98.000, "electrons": 43, "period": 5, "group": 7, "category": "Transition metal"},
    "Ru": {"name": "Ruthenium", "atomic_number": 44, "mass": 101.070, "electrons": 44, "period": 5, "group": 8, "category": "Transition metal"},
    "Rh": {"name": "Rhodium", "atomic_number": 45, "mass": 102.906, "electrons": 45, "period": 5, "group": 9, "category": "Transition metal"},
    "Pd": {"name": "Palladium", "atomic_number": 46, "mass": 106.420, "electrons": 46, "period": 5, "group": 10, "category": "Transition metal"},
    "Ag": {"name": "Silver", "atomic_number": 47, "mass": 107.868, "electrons": 47, "period": 5, "group": 11, "category": "Transition metal"},
    "Cd": {"name": "Cadmium", "atomic_number": 48, "mass": 112.411, "electrons": 48, "period": 5, "group": 12, "category": "Transition metal"},
    "In": {"name": "Indium", "atomic_number": 49, "mass": 114.818, "electrons": 49, "period": 5, "group": 13, "category": "Post-transition metal"},
    "Sn": {"name": "Tin", "atomic_number": 50, "mass": 118.710, "electrons": 50, "period": 5, "group": 14, "category": "Post-transition metal"},
    "Sb": {"name": "Antimony", "atomic_number": 51, "mass": 121.760, "electrons": 51, "period": 5, "group": 15, "category": "Metalloid"},
    "Te": {"name": "Tellurium", "atomic_number": 52, "mass": 127.600, "electrons": 52, "period": 5, "group": 16, "category": "Metalloid"},
    "I": {"name": "Iodine", "atomic_number": 53, "mass": 126.904, "electrons": 53, "period": 5, "group": 17, "category": "Halogen"},
    "Xe": {"name": "Xenon", "atomic_number": 54, "mass": 131.293, "electrons": 54, "period": 5, "group": 18, "category": "Noble gas"},
    "Cs": {"name": "Cesium", "atomic_number": 55, "mass": 132.905, "electrons": 55, "period": 6, "group": 1, "category": "Alkali metal"},
    "Ba": {"name": "Barium", "atomic_number": 56, "mass": 137.327, "electrons": 56, "period": 6, "group": 2, "category": "Alkaline earth metal"},
    "La": {"name": "Lanthanum", "atomic_number": 57, "mass": 138.905, "electrons": 57, "period": 6, "group": 3, "category": "Lanthanide"},
    "Hf": {"name": "Hafnium", "atomic_number": 72, "mass": 178.490, "electrons": 72, "period": 6, "group": 4, "category": "Transition metal"},
    "Ta": {"name": "Tantalum", "atomic_number": 73, "mass": 180.948, "electrons": 73, "period": 6, "group": 5, "category": "Transition metal"},
    "W": {"name": "Tungsten", "atomic_number": 74, "mass": 183.840, "electrons": 74, "period": 6, "group": 6, "category": "Transition metal"},
    "Re": {"name": "Rhenium", "atomic_number": 75, "mass": 186.207, "electrons": 75, "period": 6, "group": 7, "category": "Transition metal"},
    "Os": {"name": "Osmium", "atomic_number": 76, "mass": 190.230, "electrons": 76, "period": 6, "group": 8, "category": "Transition metal"},
    "Ir": {"name": "Iridium", "atomic_number": 77, "mass": 192.217, "electrons": 77, "period": 6, "group": 9, "category": "Transition metal"},
    "Pt": {"name": "Platinum", "atomic_number": 78, "mass": 195.084, "electrons": 78, "period": 6, "group": 10, "category": "Transition metal"},
    "Au": {"name": "Gold", "atomic_number": 79, "mass": 196.967, "electrons": 79, "period": 6, "group": 11, "category": "Transition metal"},
    "Hg": {"name": "Mercury", "atomic_number": 80, "mass": 200.590, "electrons": 80, "period": 6, "group": 12, "category": "Transition metal"},
    "Tl": {"name": "Thallium", "atomic_number": 81, "mass": 204.383, "electrons": 81, "period": 6, "group": 13, "category": "Post-transition metal"},
    "Pb": {"name": "Lead", "atomic_number": 82, "mass": 207.200, "electrons": 82, "period": 6, "group": 14, "category": "Post-transition metal"},
    "Bi": {"name": "Bismuth", "atomic_number": 83, "mass": 208.980, "electrons": 83, "period": 6, "group": 15, "category": "Post-transition metal"},
    "Po": {"name": "Polonium", "atomic_number": 84, "mass": 209.000, "electrons": 84, "period": 6, "group": 16, "category": "Post-transition metal"},
    "At": {"name": "Astatine", "atomic_number": 85, "mass": 210.000, "electrons": 85, "period": 6, "group": 17, "category": "Halogen"},
    "Rn": {"name": "Radon", "atomic_number": 86, "mass": 222.000, "electrons": 86, "period": 6, "group": 18, "category": "Noble gas"},
    "Fr": {"name": "Francium", "atomic_number": 87, "mass": 223.000, "electrons": 87, "period": 7, "group": 1, "category": "Alkali metal"},
    "Ra": {"name": "Radium", "atomic_number": 88, "mass": 226.000, "electrons": 88, "period": 7, "group": 2, "category": "Alkaline earth metal"},
    "Ac": {"name": "Actinium", "atomic_number": 89, "mass": 227.000, "electrons": 89, "period": 7, "group": 3, "category": "Actinide"},
    "Rf": {"name": "Rutherfordium", "atomic_number": 104, "mass": 267.000, "electrons": 104, "period": 7, "group": 4, "category": "Transition metal"},
    "Db": {"name": "Dubnium", "atomic_number": 105, "mass": 268.000, "electrons": 105, "period": 7, "group": 5, "category": "Transition metal"},
    "Sg": {"name": "Seaborgium", "atomic_number": 106, "mass": 271.000, "electrons": 106, "period": 7, "group": 6, "category": "Transition metal"},
    "Bh": {"name": "Bohrium", "atomic_number": 107, "mass": 272.000, "electrons": 107, "period": 7, "group": 7, "category": "Transition metal"},
    "Hs": {"name": "Hassium", "atomic_number": 108, "mass": 270.000, "electrons": 108, "period": 7, "group": 8, "category": "Transition metal"},
    "Mt": {"name": "Meitnerium", "atomic_number": 109, "mass": 276.000, "electrons": 109, "period": 7, "group": 9, "category": "Transition metal"},
    "Ds": {"name": "Darmstadtium", "atomic_number": 110, "mass": 281.000, "electrons": 110, "period": 7, "group": 10, "category": "Transition metal"},
    "Rg": {"name": "Roentgenium", "atomic_number": 111, "mass": 280.000, "electrons": 111, "period": 7, "group": 11, "category": "Transition metal"},
    "Cn": {"name": "Copernicium", "atomic_number": 112, "mass": 285.000, "electrons": 112, "period": 7, "group": 12, "category": "Transition metal"},
    "Nh": {"name": "Nihonium", "atomic_number": 113, "mass": 284.000, "electrons": 113, "period": 7, "group": 13, "category": "Post-transition metal"},
    "Fl": {"name": "Flerovium", "atomic_number": 114, "mass": 289.000, "electrons": 114, "period": 7, "group": 14, "category": "Post-transition metal"},
    "Mc": {"name": "Moscovium", "atomic_number": 115, "mass": 288.000, "electrons": 115, "period": 7, "group": 15, "category": "Post-transition metal"},
    "Lv": {"name": "Livermorium", "atomic_number": 116, "mass": 293.000, "electrons": 116, "period": 7, "group": 16, "category": "Post-transition metal"},
    "Ts": {"name": "Tennessine", "atomic_number": 117, "mass": 294.000, "electrons": 117, "period": 7, "group": 17, "category": "Halogen"},
    "Og": {"name": "Oganesson", "atomic_number": 118, "mass": 294.000, "electrons": 118, "period": 7, "group": 18, "category": "Noble gas"},
}

MOLECULE_FACTORY = {
    "H2O": Sphere,
}

MOLECULE_DICT = {"H2O", "CO2"}
